apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: low
  name: low
spec:
  replicas: 1
  selector:
    matchLabels:
      app: low
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: low
    spec:
      containers:
        - image: us.gcr.io/kube-flux/kube-flux-zeus:0.0.3
          name: low
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 9999
status: {}
