apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: medium
  name: medium
  namespace: final
spec:
  replicas: 10
  selector:
    matchLabels:
      app: medium
  strategy: {}
  template:
    metadata:
      annotations:
        imp: "2"
      creationTimestamp: null
      labels:
        app: medium
    spec:
      containers:
        - image: us.gcr.io/kube-flux/kube-flux-workload:0.0.2
          name: medium
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 9999
status: {}
