apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment1
  namespace: test
  labels:
    app: ngnix1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ngnix1
  template:
    metadata:
      annotations:
        imp: "1"
      labels:
        app: ngnix1
    spec:
      containers:
        - image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: ngnix1
          ports:
            - containerPort: 80
              protocol: TCP
              