apiVersion: v1
kind: Service
metadata:
  name: ngnix-deployment
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: ngnix-deployment
  type: NodePort

